# Set global values
global:
fullnameOverride: quizz

# Override polyflix service
quizz:
  image:
    repository: protocole/pdo-22-quizz
    tag: main
  service:
    port: 8080
  extraEnvVars:
    - name: "PORT"
      value: 8080

# Set service port for ingress local template
service:
  port: 8080

# Set ingress values
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: nest.ndl.thomasgouveia.fr
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nest-tls
      hosts:
        - nest.ndl.thomasgouveia.fr
