# Set global values
global:
fullnameOverride: web3

# Override polyflix service
web3:
  image:
    repository: ghcr.io/pdo-ndl-2022/web3
    tag: main
  service:
    port: 8080

# Set service port for ingress local template
service:
  port: 8080

# Set ingress values
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: web3.ndl.thomasgouveia.fr
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: web3-tls
      hosts:
        - app.ndl.thomasgouveia.fr
