apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argo-cd
spec:
  project: default
  source:
    path: helm/applications/frontend
    repoURL: https://github.com/pdo-ndl-2022/infrastructure.git
    targetRevision: HEAD
    helm:
      releaseName: frontend
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
