# Set global values
global:
fullnameOverride: frontend

# Override polyflix service
frontend:
  image:
    repository: ghcr.io/pdo-ndl-2022/frontend
    tag: main
  service:
    port: 8080
  extraEnvVars:
    - name: "PORT"
      value: 8080

# Set service port for ingress local template
service:
  port: 8080

# Set ingress values
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: app.ndl.thomasgouveia.fr
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: app-tls
      hosts:
        - app.ndl.thomasgouveia.fr
