# Override polyflix service
# ndl.thomasgouveia.fr

global:
  fullnameOverride: frontend

services:
  image:
    repository: ghcr.io/pdo-ndl-2022/frontend
    tag: main

ingress:
  enabled: true
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: ndl.thomasgouveia.fr
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
